SELECT   `FEEDENTRIES`.`url`,
         `FEEDENTRYTAGS`.`name`,
         `FEEDENTRYSTATUSES`.`read_status`,
         `FEEDENTRYSTATUSES`.`starred`,
         `FEEDENTRYCONTENTS`.`title`,
         `FEEDENTRYCONTENTS`.`content`
FROM     `FEEDENTRYSTATUSES` 
INNER JOIN `FEEDENTRIES`  ON `FEEDENTRYSTATUSES`.`entry_id` = `FEEDENTRIES`.`id` 
INNER JOIN `FEEDENTRYTAGS`  ON `FEEDENTRYTAGS`.`entry_id` = `FEEDENTRIES`.`id` 
INNER JOIN `FEEDENTRYCONTENTS`  ON `FEEDENTRIES`.`content_id` = `FEEDENTRYCONTENTS`.`id` 