/*
 * Created on 2019-08-02 ( Date ISO 2019-08-02 - Time 22:20:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package cai.peter.vision.persistence.repository;

import cai.peter.vision.persistence.entity.FeedEntry;
import cai.peter.vision.persistence.entity.FeedEntryStatus;
import cai.peter.vision.persistence.entity.FeedSubscription;
import cai.peter.vision.persistence.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Spring data Jpa repository for "Feedentrystatuses" <br>
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface FeedentrystatusesRepository extends JpaRepository<FeedEntryStatus, Long>, JpaSpecificationExecutor<FeedEntryStatus> {
//    @Query(value = "select s from FeedEntryStatus  s where s.user = ?1 and s.subscription = ?2 and s.entry = ?3")
    FeedEntryStatus getByUserAndSubscriptionAndEntry(User user, FeedSubscription sub, FeedEntry entry);

    @Query(value = "select s from FeedEntryStatus s where s.user = ?1 and s.starred = false")
    List<FeedEntryStatus> findStarred(User user);
}