/*
 * Created on 2019-08-02 ( Date ISO 2019-08-02 - Time 22:20:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package cai.peter.vision.persistence.repository;

import cai.peter.vision.persistence.entity.UserRole;
import cai.peter.vision.persistence.entity.UserRole.Role;
import java.util.Set;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

/**
 * Spring data Jpa repository for "Userroles" <br>
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface UserrolesRepository extends JpaRepository<UserRole, Long>, JpaSpecificationExecutor<UserRole> {

  @Query(value = "select r from UserRole r where r.user.id = ?1")
  Set<Role> findRoles(Long userId);

}